### ISSUE TITLE
Memory allocation error when running large grids.

### ISSUE THREAD

**Issue by calum-chamberlain** [calum-chamberlain/EQcorrscan#5]
Traceback (most recent call last):
      File "./LFE_brightness_search.py", line 130, in <module>
        brightdef.coherance)
      File "/home/calumch/my_programs/Building/EQcorrscan/core/bright_lights.py", line 355, in brightness
        energy=np.array([np.array([np.nan]*len(stream[0]))]*len(nodes))
    MemoryError

**Comment by calum-chamberlain** [comment]
Running on 64 core machine shows that it uses about 80GB of RAM when running 10 processes, about 74GB when running a linear run.

**Comment by calum-chamberlain** [comment]
It just is this way, it is hungry!
